version: '3'
services:
  chrome:
    image: "dikabrenda/cypress_project"
    command: "test"
    volumes:
      - ./cypress/videos:/cypress-project/cypress/videos
      - ./cypress/reports:/cypress-project/cypress/reports

  firefox:
    image: "dikabrenda/cypress_project"
    command: "test:firefox"
    volumes:
      - ./cypress/videos:/cypress-project/cypress/videos
      - ./cypress/reports:/cypress-project/cypress/reports