name: Dika Brenda Portofolio

on:
  push:
    branches: [ master ]
    paths-ignore:
        - '**.md'

  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  test:
    name: Regression ACV - ${{ matrix.node-version}} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: cypress/browsers:node14.17.0-chrome88-ff89

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    #Request
    - name: Telegram Notify request
      if: ${{ github.event_name == 'pull_request' }}
      uses: appleboy/telegram-action@v0.0.8
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: User ${{github.actor}} in ${{ github.repository }} repository. Make ${{ github.event_name }}. Job ${{ github.job }} URL - "${{ github.event.pull_request.title }} --> ${{ github.event.pull_request.html_url }}"
    
    #Push
    - name: Telegram Notify push
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/telegram-action@v0.0.8
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: User ${{github.actor}} in ${{ github.repository }} repository. The ${{ github.event_name }} event triggered - "${{ github.event.head_commit.message }} --> ${{ github.event.head_commit.url }}"
        
    - name: npm install
      run: |
       npm install

    - name: npm build
      run: |
       npm run build --if-present

    - name: npm test
      run: |
        npm run test
      env:
        CI: true

    # - name: attach videos and screenshot
    #   run: |
    #     mkdir public
    #     cp -r cypress/videos public/videos
    #     cp -r cypress/screenshots public/screenshots

    - name: Deploy report page to github page
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'