name: Dika Brenda Portofolio

on:
  push:
    branches: [ master ]
    paths-ignore:
        - '**.md'
  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  test:
    name: Github CI - ${{ matrix.node-version}} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - name: Declarative SCM
        uses: actions/checkout@v2

      - name: SCM
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build and Push Docker
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_IMAGE }}
          tags: v2
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}