name: Dika Brenda Portofolio

on:
  push:
    branches: [ master ]
    paths-ignore:
        - '**.md'

  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  test:
    name: Github CI - ${{ matrix.node-version}} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: cypress/browsers:node14.17.0-chrome88-ff89

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
       npm install

    - name: npm build
      run: |
       npm run build --if-present

    - name: npm test
      run: |
        npm run test
      env:
        CI: true

    # - name: attach videos and screenshot
    #   run: |
    #     mkdir public
    #     cp -r cypress/videos public/videos
    #     cp -r cypress/screenshots public/screenshots

    - name: Deploy report page to github page
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cypress/reports/mochareport
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'