name: Dika Brenda Portofolio

on:
  push:
    branches: [ master ]
    paths-ignore:
        - '**.md'

  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  test:
    name: Github CI - ${{ matrix.node-version}} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
    - name: Build and Push Docker
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: dikabrenda/cypress_project
          tags: v1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}