name: Dika Brenda Portofolio

on:
  push:
    branches: [ master ]
    paths-ignore:
        - '**.md'
  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  test:
    name: Github CI - ${{ matrix.node-version}} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    
  steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: SCM
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cypress_project:v3

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}